FROM contrail-base-u14.04:{{ contrail_version }}
COPY entrypoint.sh /
RUN chmod +x /entrypoint.sh
ENTRYPOINT /entrypoint.sh
RUN contrailctl config sync -c controller -F -v -t package
RUN contrailctl config sync -c controller -F -v -t install
EXPOSE 8082 8084 8087 8088 8096 8100 5672 5997 5998 4369 8443 8444 68 123 8103 9160 2181 9092 8092 8093 8094 8101 8083 179 53 5269 8080 8143
COPY supervisor_configs/config/ /etc/contrail/supervisord_config_files/
RUN mkdir -p /etc/contrail/supervisord_files
COPY supervisor_configs/main/supervisord.conf /etc/contrail/
COPY supervisor_configs/main/*.ini /etc/contrail/supervisord_files/
