#!/usr/bin/env bash

. common.sh

IPADDRESS=${IPADDRESS:-127.0.0.1}

CONTROL_IP=${CONTROL_IP:-$IPADDRESS}
# Control ifmap user/password are control ip address
CONTROL_IFMAP_USER=${CONTROL_IFMAP_USER:-$IPADDRESS}
CONTROL_IFMAP_PASSWORD=${CONTROL_IFMAP_PASSWORD:-$CONTROL_IFMAP_USER}
CONTROL_LOG_FILE=${CONTROL_LOG_FILE:-"/var/log/contrail/contrail-control.log"}
CONTROL_CERTS_STORE=$CONTROL_CERTS_STORE
CONTROL_LOG_LEVEL=${CONTROL_LOG_LEVEL:-"SYS_NOTICE"}

DISCOVERY_SERVER=${DISCOVERY_SERVER:-$CONTROL_IP}
DISCOVERY_PORT=${DISCOVERY_PORT:-5998}

DNS_LOG_FILE=${DNS_LOG_FILE:-"/var/log/contrail/contrail-dns.log"}
DNS_LOG_LEVEL=${DNS_LOG_LEVEL:-"SYS_NOTICE"}
DNS_IFMAP_USER=${DNS_IFMAP_USER:-${IPADDRESS}.dns}
DNS_IFMAP_PASSWORD=${DNS_IFMAP_PASSWORD:-$DNS_IFMAP_USER}
# This should be autogenerated rather than static value
DNS_RNDC_KEY=${DNS_RNDC_KEY:-"xvysmOR8lnUQRBcunkC6vg=="}


KEYSTONE_SERVER=${KEYSTONE_SERVER:-IPADDRESS}

KEYSTONE_AUTH_PROTOCOL=${KEYSTONE_AUTH_PROTOCOL:-'http'}
KEYSTONE_AUTH_PORT=${KEYSTONE_AUTH_PORT:-35357}
KEYSTONE_INSECURE=${KEYSTONE_INSECURE:-False}
KEYSTONE_ADMIN_USER=${OS_USERNAME:-"admin"}
KEYSTONE_ADMIN_PASSWORD=${OS_PASSWORD:-"secret123"}
KEYSTONE_ADMIN_TENANT=${OS_TENANT_NAME:-"admin"}
KEYSTONE_MEMCACHE_SERVERS=${KEYSTONE_MEMCACHE_SERVERS:-"127.0.0.1:11211"}
REGION=${REGION:-'RegionOne'}

# Setup contrail-control.conf
setcfg "/etc/contrail/contrail-control.conf"
setsection DEFAULT
setini hostip $IPADDRESS
setini hostname $HOSTNAME
setini log_file $CONTROL_LOG_FILE
setini log_level $CONTROL_LOG_LEVEL
setini log_local 1

setsection DISCOVERY
setini server $DISCOVERY_SERVER

setsection IFMAP
setini user $CONTROL_IFMAP_USER
setini password $CONTROL_IFMAP_PASSWORD
setini certs_store $CONTROL_CERTS_STORE

# End contrail-control.conf setup

# Setup contrail-dns.conf
setcfg "/etc/contrail/contrail-dns.conf"
setsection "DEFAULT"
setini hostip $IPADDRESS
setini hostname $HOSTNAME
setini log_file $DNS_LOG_FILE
setini log_level $DNS_LOG_LEVEL
setini log_local 1

setsection DISCOVERY
setini server $DISCOVERY_SERVER

setsection "IFMAP"
setini user $DNS_IFMAP_USER
setini password $DNS_IFMAP_PASSWORD
setini certs_store $CONTROL_CERTS_STORE
# END contrail-dns.conf


# Setup contrail-control-nodemgr.conf
setcfg "/etc/contrail/contrail-control-nodemgr.conf"
setsection "DISCOVERY"
setini server $DISCOVERY_SERVER
setini port $DISCOVERY_PORT
# END contrail-control-nodemgr.conf

setup_keystone_auth_config
setup_vnc_api_lib

# FIXME - would need to create secret rather than accept it as variable. Also may be it need better regex
#   to handle multiple space etc
for file in /etc/contrail/dns/contrail-rndc.conf /etc/contrail/dns/contrail-named.conf; do
    sed -i 's/secret \"secret123\";/secret \"${DNS_RNDC_KEY}\";/g' $file
done
