FROM contrail-base-redhat:{{ contrail_version }}
ARG CONTRAIL_VERSION
ARG OS
LABEL Name=contrail-agent-$OS \
      Version="$CONTRAIL_VERSION" \
      Description="Dockerimage for Contrail Vrouter Agent" Vendor="Juniper Networks"

RUN contrailctl config sync -c agent -F -t package
RUN contrailctl config sync -c agent -F -t install
EXPOSE 8085 9090

# Copy Empty repo file so will be overridden by hypervisor's subscription
COPY redhat.repo.empty /etc/yum.repos.d/redhat.repo

# Repo cleanup
RUN [ -f /etc/yum.repos.d/contrail-install.repo ] && \
      rm -f /etc/yum.repos.d/contrail-install.repo ; \
    yum clean all ; yum clean expire-cache ;\
    echo pass
