FROM contrail-base-u16.04:{{ contrail_version }}
LABEL Name=contrail-analytics-$OS \
      Version="$CONTRAIL_VERSION" \
      contrail.role=analytics \
      Description="Dockerimage for Contrail Analytics" Vendor="Juniper Networks"
RUN contrailctl config sync -c analytics -F -v -t package
RUN contrailctl config sync -c analytics -F -v -t install
