#!/usr/bin/env bash

source /common.sh

IPADDRESS=${IPADDRESS:-127.0.0.1}

CONFIG_IP=${CONFIG_IP:-$IPADDRESS}
CONFIG_SERVER_LIST=${CONFIG_SERVER_LIST:-$CONFIG_IP}

# Listen to standard port in case of single node setup,
# this will eliminate the need of haproxy in single node environment
num_config_servers=$(echo $CONFIG_SERVER_LIST | sed -r 's/\s+/\n/g'| wc -l)

if [[ $num_config_servers -eq 1 ]]; then
    NEUTRON_LISTEN_PORT_DEFAULT=9696
    CONFIG_API_LISTEN_PORT_DEFAULT=8082
    DISCOVERY_LISTEN_PORT_DEFAULT=5998
else
    NEUTRON_LISTEN_PORT_DEFAULT=9697
    CONFIG_API_LISTEN_PORT_DEFAULT=9100
    DISCOVERY_LISTEN_PORT_DEFAULT=9110
fi


CONTRAIL_INTERNAL_VIP=${CONTRAIL_INTERNAL_VIP}
OPENSTACK_INTERNAL_VIP=${OPENSTACK_INTERNAL_VIP}

API_SERVER_LISTEN=${API_SERVER_LISTEN:-0.0.0.0}
API_SERVER_LISTEN_PORT=${API_SERVER_LISTEN_PORT:-$CONFIG_API_LISTEN_PORT_DEFAULT}
API_SERVER_IP=${API_SERVER_IP:-${CONTRAIL_INTERNAL_VIP:-$CONFIG_IP}}
API_SERVER_PORT=${API_SERVER_PORT:-8082}
API_SERVER_USE_SSL=${API_SERVER_USE_SSL:-"False"}
MULTI_TENANCY=${MULTI_TENANCY:-True}
API_SERVER_LOG_FILE=${API_SERVER_LOG_FILE:-"/var/log/contrail/contrail-api.log"}
API_SERVER_LOG_LEVEL=${API_SERVER_LOG_LEVEL:-"SYS_NOTICE"}
API_SERVER_INSECURE=${API_SERVER_INSECURE:-"False"}
SCHEMA_LOG_FILE=${SCHEMA_LOG_FILE:-"/var/log/contrail/contrail-schema.log"}
SCHEMA_LOG_LEVEL=${SCHEMA_LOG_LEVEL:-SYS_NOTICE}

# Rabbitmq server list is a comma seperated list of rabbitmq server *NAMES* which are
# resolvable from the container or a list of ip1:host1,ip2:host2. e.g, 192.168.0.10:rabbit1,192.168.0.11:rabbit2
RABBITMQ_SERVER_LIST=${RABBITMQ_SERVER_LIST:-"$IPADDRESS:$HOSTNAME"}
RABBITMQ_SERVER_PORT=${RABBITMQ_SERVER_PORT:-5672}
RABBITMQ_LISTEN_IP=${RABBITMQ_LISTEN_IP:-$IPADDRESS}
ENABLE_RABBITMQ=${ENABLE_RABBITMQ}
RABBITMQ_CLUSTER_UUID=${RABBITMQ_CLUSTER_UUID}

[[ $RABBITMQ_CLUSTER_UUID ]] || fail "Rabbitmq erlang cookie must be set in the variable \$RABBITMQ_CLUSTER_UUID."

ANALYTICS_SERVER=${ANALYTICS_SERVER:-${CONTRAIL_INTERNAL_VIP:-$IPADDRESS}}
ANALYTICS_SERVER_PORT=${ANALYTICS_SERVER_PORT:-8081}

CASSANDRA_SERVER_LIST=${CASSANDRA_SERVER_LIST:-$IPADDRESS}
CASSANDRA_SERVER_PORT=${CASSANDRA_SERVER_PORT:-9160}
ZOOKEEPER_SERVER_LIST=${ZOOKEEPER_SERVER_LIST:-$IPADDRESS}
ZOOKEEPER_SERVER_PORT=${ZOOKEEPER_SERVER_PORT:-2181}
CONTROL_SERVER_LIST=${CONTROL_SERVER_LIST:-$IPADDRESS}

IFMAP_SERVER=${IFMAP_SERVER:-$IPADDRESS}
IFMAP_SERVER_PORT=${IFMAP_SERVER_PORT:-8443}
IFMAP_USERNAME=${IFMAP_USERNAME:-"api-server"}
IFMAP_PASSWORD=${IFMAP_PASSWORD:-"api-server"}

DISCOVERY_SERVER=${DISCOVERY_SERVER:-${CONTRAIL_INTERNAL_VIP:-$CONFIG_IP}}
DISCOVERY_SERVER_LISTEN=${DISCOVERY_SERVER_LISTEN:-"0.0.0.0"}
DISCOVERY_SERVER_LISTEN_PORT=${DISCOVERY_SERVER_LISTEN_PORT:-$DISCOVERY_LISTEN_PORT_DEFAULT}
DISCOVERY_SERVER_PORT=${DISCOVERY_SERVER_PORT:-5998}
DISCOVERY_LOG_FILE=${DISCOVERY_LOG_FILE:-"/var/log/contrail/contrail-discovery.log"}
DISCOVERY_LOG_LEVEL=${DISCOVERY_LOG_LEVEL:-"SYS_NOTICE"}
DISCOVERY_TTL_MIN=${DISCOVERY_TTL_MIN:-300}
DISCOVERY_TTL_MAX=${DISCOVERY_TTL_MAX:-1800}
DISCOVERY_HC_INTERVAL=${DISCOVERY_HC_INTERVAL:-5}
DISCOVERY_HC_MAX_MISS=${DISCOVERY_HC_MAX_MISS:-3}
DISCOVERY_TTL_SHORT=${DISCOVERY_TTL_SHORT:-1}
DISCOVERY_DNS_SERVER_POLICY=${DISCOVERY_DNS_SERVER_POLICY:-fixed}

SVC_MONITOR_LOG_FILE=${SVC_MONITOR_LOG_FILE:-"/var/log/contrail/contrail-svc-monitor.log"}
SVC_MONITOR_LOG_LEVEL=${SVC_MONITOR_LOG_LEVEL:-SYS_NOTICE}


COLLECTOR_SERVER=${COLLECTOR_SERVER:-${CONTRAIL_INTERNAL_VIP:-$CONFIG_IP}}

KEYSTONE_SERVER=${KEYSTONE_SERVER:-${OPENSTACK_INTERNAL_VIP:-$IPADDRESS}}


SERVICE_TENANT=${SERVICE_TENANT:-service}
KEYSTONE_AUTH_PROTOCOL=${KEYSTONE_AUTH_PROTOCOL:-http}
KEYSTONE_AUTH_PORT=${KEYSTONE_AUTH_PORT:-35357}
KEYSTONE_INSECURE=${KEYSTONE_INSECURE:-False}
KEYSTONE_ADMIN_USER=${OS_USERNAME:-admin}
KEYSTONE_ADMIN_PASSWORD=${OS_PASSWORD:-admin}
KEYSTONE_ADMIN_TENANT=${OS_TENANT_NAME:-admin}
KEYSTONE_ADMIN_TOKEN=${OS_TOKEN:-$ADMIN_TOKEN}
REGION=${REGION:-RegionOne}

NEUTRON_IP=${NEUTRON_IP:-${CONTRAIL_INTERNAL_VIP:-$CONFIG_IP}}
NEUTRON_PORT=${NEUTRON_PORT:-$NEUTRON_LISTEN_PORT_DEFAULT}
NEUTRON_USER=${NEUTRON_USER:-neutron}

NEUTRON_PASSWORD=${NEUTRON_PASSWORD:-neutron}
NEUTRON_PROTOCOL=${KEYSTONE_AUTH_PROTOCOL:-http}
CONTRAIL_EXTENSIONS_DEFAULTS="ipam:neutron_plugin_contrail.plugins.opencontrail.contrail_plugin_ipam.NeutronPluginContrailIpam,policy:neutron_plugin_contrail.plugins.opencontrail.contrail_plugin_policy.NeutronPluginContrailPolicy,route-table:neutron_plugin_contrail.plugins.opencontrail.contrail_plugin_vpc.NeutronPluginContrailVpc,contrail:None"
NEUTRON_CONTRAIL_EXTENSIONS=${NEUTRON_CONTRAIL_EXTENSIONS:-$CONTRAIL_EXTENSIONS_DEFAULTS}
NEUTRON_SERVER_LIST=${NEUTRON_SERVER_LIST:-$CONFIG_SERVER_LIST}

