FROM contrail-base-ubuntu14.04:{{ contrail_version }}
LABEL Name=contrail-analyticsdb-$OS \
      Version="$CONTRAIL_VERSION" \
      contrail.role=analyticsdb \
      Description="Contrail AnalyticsDB" Vendor="Juniper Networks"
COPY entrypoint.sh /
RUN chmod +x /entrypoint.sh
ENTRYPOINT /entrypoint.sh
ENV CONTRAIL_ROLE analyticsdb
RUN echo $CONTRAIL_ROLE > /etc/contrail-role
RUN contrailctl config sync -F -v -t package
RUN contrailctl config sync  -F -v -t install
EXPOSE 9161 9141
