FROM contrail-base-ubuntu14.04:{{ contrail_version }}
LABEL Name=contrail-analyticsdb-$OS \
      Version="$CONTRAIL_VERSION" \
      contrail.role=analyticsdb \
      Description="Contrail AnalyticsDB" Vendor="Juniper Networks"
COPY entrypoint.sh /
RUN chmod +x /entrypoint.sh
ENTRYPOINT /entrypoint.sh
RUN contrailctl config sync -c analyticsdb -F -v -t package
RUN contrailctl config sync -c analyticsdb -F -v -t install
EXPOSE 9161 9141
