FROM contrail-base-u14.04:{{ contrail_version }}
COPY entrypoint.sh /
LABEL Name=contrail-agent-$OS \
      Version="$CONTRAIL_VERSION" \
      contrail.role=agent \
      Description="Dockerimage for Contrail Vrouter Agent" Vendor="Juniper Networks"
RUN chmod +x /entrypoint.sh
ENTRYPOINT /entrypoint.sh
RUN contrailctl config sync -c agent -F -v -t package
RUN contrailctl config sync -c agent -F -v -t install
EXPOSE 8085 9090
RUN cp -rf /usr/src/ /usr/src.orig/
