FROM contrail-base-u14.04:{{ contrail_version }}
COPY entrypoint.sh /
RUN chmod +x /entrypoint.sh
ENTRYPOINT /entrypoint.sh
RUN contrailctl config sync -c kubemanager -F -v -t package
RUN contrailctl config sync -c kubemanager -F -v -t install
