FROM contrail-base-ubuntu14.04:{{ contrail_version }}
LABEL Name=storage-ceph-controller-$OS \
      Version="$CONTRAIL_VERSION" \
      contrail.role=ceph-controller \
      Description="Dockerimage for Contrail Ceph Controller" Vendor="Juniper Networks"
COPY entrypoint.sh /
RUN chmod +x /entrypoint.sh
ENTRYPOINT /entrypoint.sh
RUN contrailctl config sync -c cephcontroller -F -v -t install
EXPOSE 6789 6005 6006
