FROM contrail-base-redhat7:{{ contrail_version }}
ARG CONTRAIL_VERSION
ARG OS
LABEL Name=contrail-analyticsdb-$OS \
      Version="$CONTRAIL_VERSION" \
      Description="Dockerimage for Contrail AnalyticsDB" Vendor="Juniper Networks"

RUN contrailctl config sync -c analyticsdb -F -t package
RUN contrailctl config sync -c analyticsdb -F -t install
EXPOSE 9141 9161

# Repo cleanup
RUN [ -f /etc/yum.repos.d/contrail-install.repo ] && \
      rm -f /etc/yum.repos.d/contrail-install.repo ; \
    yum clean all ; yum clean expire-cache ;\
    echo pass

