FROM contrail-base-u16.04:{{ contrail_version }}
RUN contrailctl config sync -c agent -F -t package
RUN contrailctl config sync -c agent -F -t install
EXPOSE 8085 9090
RUN cp -rf /usr/src/ /usr/src.orig/
