name: Contrail
description: A Helm chart for contrail
version: 4.0.1.0
appVersion: Contrail 4.0.1.0
home: https://github.com/Juniper/contrail-docker/
sources:
  - https://github.com/Juniper/contrail-controller/
tillerVersion: ">=2.4.0"
keywords:
  - Contrail
  - SDN
