FROM contrail-base-u14.04:{{ contrail_version }}
COPY entrypoint.sh /
RUN chmod +x /entrypoint.sh
ENTRYPOINT /entrypoint.sh
RUN contrailctl config sync -c analyticsdb -F -t package
RUN contrailctl config sync -c analyticsdb -F -t install
EXPOSE 9161 9141
