FROM contrail-base-ubuntu16.04:{{ contrail_version }}
LABEL Name=contrail-analytics-$OS \
      Version="$CONTRAIL_VERSION" \
      contrail.role=analytics \
      Description="Contrail Analytics" Vendor="Juniper Networks"
ENV CONTRAIL_ROLE analytics
RUN echo $CONTRAIL_ROLE > /etc/contrail-role
RUN contrailctl config sync -F -v -t package
RUN contrailctl config sync -F -v -t install
