FROM contrail-base-ubuntu14.04:{{ contrail_version }}
LABEL Name=contrail-kube-manager-$OS \
      Version="$CONTRAIL_VERSION" \
      contrail.role=kube-manager \
      Description="Contrail kube manager" Vendor="Juniper Networks"
COPY entrypoint.sh /
RUN chmod +x /entrypoint.sh
ENTRYPOINT /entrypoint.sh
RUN contrailctl config sync -c kubemanager -F -v -t package
RUN contrailctl config sync -c kubemanager -F -v -t install
