FROM contrail-base-redhat:{{ contrail_version }}
ARG CONTRAIL_VERSION
ARG OS
LABEL Name=contrail-controller-$OS \
      Version="$CONTRAIL_VERSION" \
      Description="Dockerimage for Contrail Controller" Vendor="Juniper Networks"

RUN contrailctl config sync -c controller -F -t package
RUN contrailctl config sync -c controller -F -t install
EXPOSE 53 68 123 179 2181 4369 \
       5269 5672 5997 5998 \
       8080 8082 8083 8084 8087 8088 8092 8093 8094 8096 8100 8101 8103 8143 8443 8444 \
       9092 9160

# Copy Empty repo file so will be overridden by hypervisor's subscription
COPY redhat.repo.empty /etc/yum.repos.d/redhat.repo

# Repo cleanup
RUN [ -f /etc/yum.repos.d/contrail-install.repo ] && \
      rm -f /etc/yum.repos.d/contrail-install.repo ; \
    yum clean all ; yum clean expire-cache ;\
    echo pass
