#!/usr/bin/env bash
source /common.sh

IPADDRESS=${IPADDRESS:-${primary_ip}}

CLOUD_ORCHESTRATOR=${CLOUD_ORCHESTRATOR:-"openstack"}

if [[ $CLOUD_ORCHESTRATOR == "openstack" ]]; then
    MULTI_TENANCY=${MULTI_TENANCY:-True}
else
    MULTI_TENANCY=False
fi

COMPILE_VROUTER_MODULE=${COMPILE_VROUTER_MODULE:-"yes"}
VIRTUAL_HOST_INTERFACE=${VIRTUAL_HOST_INTERFACE:-vhost0}
VIRTUAL_HOST_INTERFACE_IP_WITH_MASK=$(ip a l $primary_if | awk '/inet / {print $2}')
VIRTUAL_HOST_INTERFACE_IP=${VIRTUAL_HOST_INTERFACE_IP:-$IPADDRESS}
DISCOVERY_SERVER=${DISCOVERY_SERVER:-$CONFIG_IP}
DISCOVERY_PORT=${DISCOVERY_PORT:-5998}

VROUTER_PHYSICAL_INTERFACE=${VROUTER_PHYSICAL_INTERFACE:-$primary_if}
NODE_GATEWAY=${NODE_GATEWAY:-$gateway}
VROUTER_PHYSICAL_INTERFACE_MAC=${VROUTER_PHYSICAL_INTERFACE_MAC:-$primary_mac}

VROUTER_AGENT_LOG_FILE=${VROUTER_AGENT_LOG_FILE:-"/var/log/contrail/contrail-vrouter-agent.log"}
VROUTER_AGENT_LOG_LEVEL=${VROUTER_AGENT_LOG_LEVEL:-SYS_NOTICE}

KEYSTONE_SERVER=${KEYSTONE_SERVER:-$IPADDRESS}

KEYSTONE_AUTH_PROTOCOL=${KEYSTONE_AUTH_PROTOCOL:-http}
KEYSTONE_AUTH_PORT=${KEYSTONE_AUTH_PORT:-35357}
KEYSTONE_INSECURE=${KEYSTONE_INSECURE:-False}
KEYSTONE_ADMIN_USER=${OS_USERNAME:-admin}
KEYSTONE_ADMIN_PASSWORD=${OS_PASSWORD:-admin}
KEYSTONE_ADMIN_TENANT=${OS_TENANT_NAME:-admin}

REGION=${REGION:-RegionOne}

CONFIG_API_PORT=${CONFIG_API_PORT:-8082}
if [[ ! $NO_PROBE ]]; then
    CONFIG_IP=$(retry get_right_ip config ${CONFIG_IP:-$IPADDRESS} $CONFIG_API_PORT)
else
    CONFIG_IP=${CONFIG_IP:-$IPADDRESS}
fi
