#!/usr/bin/env bash
source /common.sh

IPADDRESS=${IPADDRESS:-${primary_ip}}

CONFIG_IP=${CONFIG_IP:-$IPADDRESS}
CONFIG_API_PORT=${CONFIG_API_PORT:-8082}

ANALYTICS_IP=${ANALYTICS_IP:-$IPADDRESS}

CASSANDRA_SERVER_LIST=${CASSANDRA_SERVER_LIST:-$IPADDRESS}
CASSANDRA_SERVER_PORT=${CASSANDRA_SERVER_PORT:-9160}

KAFKA_ENABLED=$KAFKA_ENABLED
KAFKA_BROKER_LIST=${KAFKA_BROKER_LIST:-$CASSANDRA_SERVER_LIST}
KAFKA_PORT=${KAFKA_PORT:-9092}

ZOOKEEPER_SERVER_LIST=${ZOOKEEPER_SERVER_LIST:-$CASSANDRA_SERVER_LIST}
ZOOKEEPER_SERVER_PORT=${ZOOKEEPER_SERVER_PORT:-2181}

ALARM_GEN_LOG_FILE=${CONTROL_LOG_FILE:-"/var/log/contrail/contrail-alarm-gen.log"}
ALARM_GEN_LOG_LEVEL=${CONTROL_LOG_LEVEL:-"SYS_NOTICE"}

COLLECTOR_INTROSPECT_PORT=${COLLECTOR_INTROSPECT_PORT:-8089}
COLLECTOR_PORT=${COLLECTOR_PORT:-8086}
COLLECTOR_LOG_FILE=${COLLECTOR_LOG_FILE:-"/var/log/contrail/contrail-collector.log"}
COLLECTOR_LOG_LEVEL=${COLLECTOR_LOG_LEVEL:-"SYS_NOTICE"}

ANALYTICS_SYSLOG_PORT=${ANALYTICS_SYSLOG_PORT:-1}

QUERY_ENGINE_INTROSPECT_PORT=${QUERY_ENGINE_INTROSPECT_PORT:-8091}
QUERY_ENGINE_LOG_FILE=${QUERY_ENGINE_LOG_FILE:-"/var/log/contrail/contrail-query-engine.log"}
QUERY_ENGINE_LOG_LEVEL=${QUERY_ENGINE_LOG_LEVEL:-"SYS_NOTICE"}

ANALYTICS_API_INTROSPECT_PORT=${ANALYTICS_API_INTROSPECT_PORT:-8090}
ANALYTICS_API_PORT=${ANALYTICS_API_PORT:-8081}
ANALYTICS_API_LISTEN_IP=${ANALYTICS_API_LISTEN_IP:-"0.0.0.0"}
ANALYTICS_API_LOG_FILE=${ANALYTICS_API_LOG_FILE:-"/var/log/contrail/contrail-analytics-api.log"}
ANALYTICS_API_LOG_LEVEL=${ANALYTICS_API_LOG_LEVEL:-"SYS_NOTICE"}

SNMP_COLLECTOR_LISTEN_IP=${SNMP_COLLECTOR_LISTEN_IP:-"0.0.0.0"}
SNMP_COLLECTOR_INTROSPECT_PORT=${SNMP_COLLECTOR_INTROSPECT_PORT:-5920}
SNMP_COLLECTOR_LOG_FILE=${SNMP_COLLECTOR_LOG_FILE:-"/var/log/contrail/contrail-snmp-collector.log"}
SNMP_COLLECTOR_LOG_LEVEL=${SNMP_COLLECTOR_LOG_LEVEL:-"SYS_NOTICE"}

TOPOLOGY_INTROSPECT_PORT=${TOPOLOGY_INTROSPECT_PORT:-5921}
TOPOLOGY_LOG_FILE=${TOPOLOGY_LOG_FILE:-"/var/log/contrail/contrail-topology.log"}
TOPOLOGY_LOG_LEVEL=${TOPOLOGY_LOG_LEVEL:-"SYS_NOTICE"}

ANALYTICS_DATA_TTL=${ANALYTICS_DATA_TTL:-48}
ANALYTICS_CONFIG_AUDIT_TTL=${ANALYTICS_CONFIG_AUDIT_TTL:-$ANALYTICS_DATA_TTL}
ANALYTICS_STATISTICS_TTL=${ANALYTICS_STATISTICS_TTL:-$ANALYTICS_DATA_TTL}
ANALYTICS_FLOW_TTL=${ANALYTICS_FLOW_TTL:-$ANALYTICS_DATA_TTL}

DISCOVERY_SERVER=${DISCOVERY_SERVER:-$CONFIG_IP}
DISCOVERY_PORT=${DISCOVERY_PORT:-5998}

REDIS_SERVER=${REDIS_SERVER:-$IPADDRESS}
REDIS_SERVER_PORT=${REDIS_SERVER_PORT:-6379}

KEYSTONE_SERVER=${KEYSTONE_SERVER:-$IPADDRESS}

KEYSTONE_AUTH_PROTOCOL=${KEYSTONE_AUTH_PROTOCOL:-http}
KEYSTONE_AUTH_PORT=${KEYSTONE_AUTH_PORT:-35357}
KEYSTONE_INSECURE=${KEYSTONE_INSECURE:-False}
KEYSTONE_ADMIN_USER=${OS_USERNAME:-admin}
KEYSTONE_ADMIN_PASSWORD=${OS_PASSWORD:-admin}
KEYSTONE_ADMIN_TENANT=${OS_TENANT_NAME:-admin}

REGION=${REGION:-RegionOne}
