FROM contrail-base-ubuntu14.04:{{ contrail_version }}
LABEL Name=contrail-mesos-manager-$OS \
      Version="$CONTRAIL_VERSION" \
      contrail.role=mesos-manager \
      Description="Contrail Mesos Manager" Vendor="Juniper Networks"
COPY entrypoint.sh /
RUN chmod +x /entrypoint.sh
ENTRYPOINT /entrypoint.sh
ENV CONTRAIL_ROLE mesosmanager
RUN echo $CONTRAIL_ROLE > /etc/contrail-role
RUN contrailctl config sync -F -v -t install
