FROM contrail-base-ubuntu16.04:{{ contrail_version }}
LABEL Name=contrail-kube-manager-$OS \
      Version="$CONTRAIL_VERSION" \
      contrail.role=kube-manager \
      Description="Contrail Kube manager" Vendor="Juniper Networks"
RUN contrailctl config sync -c kubemanager -F -v -t install
