FROM contrail-base-ubuntu14.04:{{ contrail_version }}
LABEL Name=contrail-lb-$OS \
      Version="$CONTRAIL_VERSION" \
      contrail.role=lb \
      Description="Contrail LB" Vendor="Juniper Networks"
COPY entrypoint.sh /
RUN chmod +x /entrypoint.sh
ENTRYPOINT /entrypoint.sh
ENV CONTRAIL_ROLE lb
RUN echo $CONTRAIL_ROLE > /etc/contrail-role
RUN contrailctl config sync -F -v -t install
EXPOSE 8082 5998 9696 8081
