FROM contrail-base-ubuntu16.04:{{ contrail_version }}
LABEL Name=contrail-analyticsdb-$OS \
      Version="$CONTRAIL_VERSION" \
      contrail.role=analyticsdb \
      Description="Contrail AnalyticsDB" Vendor="Juniper Networks"
ENV CONTRAIL_ROLE analyticsdb
RUN echo $CONTRAIL_ROLE > /etc/contrail-role
RUN contrailctl config sync -F -v -t package
RUN contrailctl config sync -F -v -t install
