FROM contrail-base-ubuntu16.04:{{ contrail_version }}
LABEL Name=contrail-analyticsdb-$OS \
      Version="$CONTRAIL_VERSION" \
      contrail.role=analyticsdb \
      Description="Contrail AnalyticsDB" Vendor="Juniper Networks"
RUN contrailctl config sync -c analyticsdb -F -v -t package
RUN contrailctl config sync -c analyticsdb -F -v -t install
