FROM contrail-base-redhat7:{{ contrail_version }}
ARG CONTRAIL_VERSION
ARG OS
LABEL Name=contrail-lb-$OS \
      Version="$CONTRAIL_VERSION" \
      Description="Dockerimage for Contrail LB" Vendor="Juniper Networks"

RUN contrailctl config sync -c lb -F -v -t install
EXPOSE 5998 8081 8082 9696

# Repo cleanup
RUN [ -f /etc/yum.repos.d/contrail-install.repo ] && \
      rm -f /etc/yum.repos.d/contrail-install.repo ; \
    yum clean all ; yum clean expire-cache ;\
    echo pass
